version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
    open-pull-requests-limit: 3
    groups:
      patch-updates:
        patterns: [ "*" ]
        update-types: [ "patch" ]
    ignore:
      - dependency-name: "org.jetbrains.kotlin*"
        versions: ["2.1.x"] # Ignore minor updates for Kotlin
    commit-message:
      prefix: "build"
      include: "scope"
