[versions]
# Production dependency versions
h2Version = "2.3.232"
hibernateVersion = "6.6.8.Final"
jakartaVersion = "3.1.0"
kotlinVersion = "2.1.0"

# Test dependency versions
assertjVersion = "3.27.3"
junit5Version = "5.11.4"

# Build dependency versions
dokkaVersion = "2.0.0"
detektVersion = "1.23.7"

[libraries]
# Production libraries
h2 = { group = "com.h2database", name = "h2", version.ref = "h2Version" }
hibernate = { group = "org.hibernate", name = "hibernate-core", version.ref = "hibernateVersion" }
jakarta = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jakartaVersion" }

# Test libraries
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertjVersion" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5Version" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5Version" }

# Build libraries

[bundles]
# Production bundles

# Test bundles
test = ["assertj", "junit-api"]

# Build bundles

[plugins]
allopen = {id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlinVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaVersion" }
jpa = {id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlinVersion" }
jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
noarg = {id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlinVersion" }