[versions]
# Production dependency versions
hibernateVersion = "6.6.13.Final"
hikari = "6.3.0"
jakartaVersion = "3.2.0"
kotlinVersion = "2.1.20"
log4j = "2.24.3"
mockk = "1.14.0"
postgres = "42.7.5"
slf4j = "2.0.17"

# Test dependency versions
assertjVersion = "3.27.3"
junit5Version = "5.12.2"
junit-platform-suite = "1.12.2"
testcontainers = "1.20.6"

# Build dependency versions
dokkaVersion = "2.0.0"
detektVersion = "1.23.8"

[libraries]
# Production libraries
hibernate = { group = "org.hibernate", name = "hibernate-core", version.ref = "hibernateVersion" }
jakarta = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jakartaVersion" }
log4j-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
postgres-driver = { group = "org.postgresql", name = "postgresql", version.ref = "postgres"}
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# Test libraries
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertjVersion" }
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5Version" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5Version" }
junit-platform-suite = { group = 'org.junit.platform', name = 'junit-platform-suite', version.ref = "junit-platform-suite" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

# Build libraries
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "kotlinVersion" }
noarg = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlinVersion" }

[bundles]
# Production bundles

# Test bundles
test = ["assertj", "junit-api", "junit-platform-suite", "mockk"]
integration-test = ["hikari", "testcontainers-postgres"]

# Build bundles

[plugins]
allopen = {id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlinVersion" }
